# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 32 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
Defaults: &defaults

  admin_name: Administrator
  admin_email: admin@example.com
  admin_password: changeme_y7keJVdqp4DR66TDeGTs

  encryption_key: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' # <Run rake secret to get a value to put here (64 characters)>

  # Main application settings
  application_name: "Adhesion"
  application_main_domain: <%= %Q{#{ENV["APP_SUBDOMAIN"]}.#{ENV["APP_ROOT_DOMAIN"] || "lvh.me"}} %>

  # Email Settings
  application_root_domain: <%= ENV["APP_ROOT_DOMAIN"] || "example.com" %>
  email_provider_username: admin@example.com
  email_provider_password: changeme

  # Assets (webpack server in dev mode)
  assets_url: <%= ENV["ASSETS_URL"] || "http://localhost:8080" %>

  canvas_url: <%= ENV["APP_DEFAULT_CANVAS_URL"] || "https://canvas.instructure.com" %>
  # Obtain a Canvas Developer ID and Key for the from an Account Admin for
  # the instance of Canvas to install the app into. ID and Keys are specific
  # to a Canvas instance (they are not global like they used to be).
  # This key and secret is used for the OAuth dance with Canvas
  canvas_developer_id: <%= ENV["CANVAS_DEVELOPER_ID"] || 1234 %>
  canvas_developer_key: <%= ENV["CANVAS_DEVELOPER_KEY"] || 'abc123' %>
  canvas_token: <%= ENV["CANVAS_TOKEN"] || "access_token" %>

  auth0_client_id: adhesion
  auth0_client_secret: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>
  shared_auth_secret: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>
  shared_sis_auth_secret: "f1a7a969973c043094e0de746084faa1" # <Run rake secret to get a value to put here>

  deploy_env: ""
  display_env: ""
  secret_token: ""

  scorm_url: <%= ENV["SCORM_URL"] || "https://localhost:8443" %>
  scorm_api_path: <%= ENV["SCORM_API_PATH"] || "/ScormEngineInterface/api/v1/" %>
  scorm_api_username: <%= ENV["SCORM_API_USERNAME"] || "apiuser" %>
  scorm_api_password: <%= ENV["SCORM_API_PASSWORD"] || "password" %>
  proctor_login_secret: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>
  canvas_proctor_url: <%= ENV["CANVAS_PROCTOR_URL"] || "example.com" %>
  u4sm_url: "https://example.com"
  u4sm_username: "username"
  u4sm_password: "password"

  error_email: ""

  storage_mount: ""
development:
  <<: *defaults

  secret_key_base: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>

  scorm_cloud_app_id: <%= ENV["SCORM_CLOUD_APP_ID"] || "id" %>
  scorm_cloud_secret_key: <%= ENV["SCORM_CLOUD_SECRET_KEY"] || "key" %>

test:
  <<: *defaults

  proctor_login_secret: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>
  secret_key_base: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>
  scorm_cloud_app_id: <%= ENV["SCORM_CLOUD_APP_ID"] %>
  scorm_cloud_secret_key: <%= ENV["SCORM_CLOUD_SECRET_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults

  secret_key_base: 'f1a7a969973c043094e0de746084faa1'

  canvas_url: "https://canvas.instructure.com"

  encryption_key: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>

  scorm_cloud_app_id: 'id'
  scorm_cloud_secret_key: 'key'

staging:
  <<: *defaults

  secret_key_base: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>

  canvas_url: "https://canvas.test.instructure.com"

  encryption_key: 'f1a7a969973c043094e0de746084faa1' # <Run rake secret to get a value to put here>
